# Generated by Django 2.0.5 on 2018-05-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_auto_20180509_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestables',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x7ff9521d7620>', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
