# Generated by Django 2.0.5 on 2018-05-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0008_auto_20180509_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestables',
            name='id',
            field=models.IntegerField(default=861567, editable=False, primary_key=True, serialize=False),
        ),
    ]
