# Generated by Django 2.0.5 on 2018-05-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0009_auto_20180509_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestables',
            name='id',
            field=models.IntegerField(default=50368635, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='id',
            field=models.IntegerField(default=14524033, editable=False, primary_key=True, serialize=False),
        ),
    ]
