# Generated by Django 2.0.5 on 2018-05-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0013_auto_20180509_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestables',
            name='id',
            field=models.IntegerField(default=81780682, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='id',
            field=models.IntegerField(default=10507135, editable=False, primary_key=True, serialize=False),
        ),
    ]
