# Generated by Django 2.0.3 on 2018-05-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En prestamo', 'En prestamo'), ('En reparacion', 'En reparacion')], default='Disponible', max_length=15)),
                ('solicitudes', models.IntegerField(default=0)),
                ('imagen', models.ImageField(default='img/none.png', upload_to='img')),
                ('sala', models.BooleanField()),
                ('color_calendario', models.CharField(default='none', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Vigente', 'Vigente'), ('Caducado', 'Caducado'), ('Perdido', 'Perdido')], max_length=15)),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingAdmin.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('permisos', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingAdmin.Usuario'),
        ),
    ]
