# Generated by Django 2.0.3 on 2018-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Vigente', 'Vigente'), ('Caducado', 'Caducado'), ('Perdido', 'Perdido')], max_length=15),
        ),
    ]
