# Generated by Django 2.0.3 on 2018-05-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingAdmin', '0002_auto_20180507_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='sala',
            new_name='espacio',
        ),
    ]
