# Generated by Django 2.0.3 on 2018-05-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingAdmin', '0003_auto_20180507_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Vigente', 'Vigente'), ('Rechazado', 'Rechazado'), ('Caducado', 'Caducado'), ('Perdido', 'Perdido')], max_length=15),
        ),
    ]
