# Generated by Django 2.0.5 on 2018-05-09 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aforo',
            fields=[
                ('capacidad', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prestables',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En prestamo', 'En prestamo'), ('En reparacion', 'En reparacion'), ('Perdido', 'Perdido')], default='Disponible', max_length=15)),
                ('imagen', models.ImageField(default='img/none.png', upload_to='img')),
                ('descripcion', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_sol', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ficha.Solicitudes')),
                ('estado_sol', models.CharField(choices=[('Vigente', 'Vigente'), ('Caducada', 'Caducada'), ('Perdida', 'Perdida')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='id_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.Prestables'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='rut_per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.Profile'),
        ),
        migrations.AddField(
            model_name='aforo',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.Prestables'),
        ),
    ]
