# Generated by Django 2.0.5 on 2018-05-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20180509_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ficha.Solicitudes'),
        ),
    ]
