# Generated by Django 2.0.5 on 2018-05-18 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20180518_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='tiempo_final',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 21, 3, 15, 186012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='tiempo_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 21, 3, 15, 185990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='tiempo_solicitud',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 21, 3, 15, 186027, tzinfo=utc)),
        ),
    ]
