# Generated by Django 2.0.5 on 2018-05-18 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_auto_20180518_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='tiempo_final',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='tiempo_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='tiempo_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
