# Generated by Django 2.0.5 on 2018-05-09 22:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_auto_20180509_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestables',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
