# Generated by Django 2.0.5 on 2018-05-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0011_auto_20180509_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestables',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
