# Generated by Django 2.0.5 on 2018-05-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_auto_20180509_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestables',
            name='id',
            field=models.IntegerField(default=58971919, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='id',
            field=models.IntegerField(default=41029248, editable=False, primary_key=True, serialize=False),
        ),
    ]
