# Generated by Django 2.0.5 on 2018-05-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_auto_20180509_2241'),
        ('ficha', '0014_auto_20180509_1937'),
    ]

    operations = [
    ]
