# Generated by Django 2.0.5 on 2018-05-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0015_merge_20180509_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamos',
            old_name='id',
            new_name='solicitud_aceptada',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='id_obj',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='rut_per',
        ),
        migrations.AddField(
            model_name='aforo',
            name='espacio',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.Prestables'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='persona',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.Profile'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='prestable',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.Prestables'),
        ),
        migrations.AlterField(
            model_name='aforo',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aforo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
