# Generated by Django 2.0.5 on 2018-06-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aforo',
            name='espacio',
        ),
        migrations.AlterField(
            model_name='aforo',
            name='id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.Prestables'),
        ),
    ]
