# Generated by Django 2.0.5 on 2018-07-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userSystem', '0001_initial'),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='persona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userSystem.Usuarios'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='prestable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.Prestables'),
        ),
        migrations.AddField(
            model_name='aforo',
            name='espacio',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.Prestables'),
        ),
    ]
