# Generated by Django 2.0.5 on 2018-05-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180523_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('solicitud_aceptada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='App.Solicitudes')),
                ('estado_sol', models.CharField(choices=[('Vigente', 'Vigente'), ('Caducada', 'Caducada'), ('Perdida', 'Perdida')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='prestables',
            name='numsolic',
            field=models.IntegerField(default=0),
        ),
    ]
